# hydra config
hydra:
  run:
    dir: ${paths.log_path}
  job:
    chdir: false

# Path
paths:
  log_path: logs/sam3d-body/${infer.type}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  video_path: /mnt/code-luoxi-pegasus/MAC_ACM_MM/data/video
  output_path: /mnt/code-luoxi-pegasus/MAC_ACM_MM/data/sam3d_body

# Model
model:
  root_path: /mnt/code-luoxi-pegasus/MAC_ACM_MM/MAC_PyTorch/ckpt/sam-3d-body-dinov3
  checkpoint_path: ${model.root_path}/model.ckpt
  mhr_path: ${model.root_path}/assets/mhr_model.pt

  # detector_name: yolov8n
  # segmentor_name: sam_vit_b
  fov_name: moge2

visualize:
  save_video: true
  plot_3d: true
  plot_2d: false
  plot_skeleton: true
  plot_skeleton_3d: true

infer:
  type: video
  conf_thres: 50.0
  keep_frames: true
  num_inference_steps: 4

  # Device can be an int/list (e.g. 0 or [0,1]) or "cpu"
  gpu: 0

  # Action-based parallel workers per device
  workers_per_gpu: 5

  data_types: [train, val, test]