# hydra config
hydra:
  run:
    dir: ${log_path} # the log path, used for log and checkpoint
  sweep:
    dir: logs/
    subdir: ${experiment}/${now:%Y-%m-%d}/${now:%H-%M-%S}

loss:
  lr: 0.001
  weight_decay: 0.01

  fine_loss_weight: 1.0
  coarse_loss_weight: 0.5

data:
  video_root: "/mnt/code-luoxi-pegasus/MAC_ACM_MM/data/video"
  sam3d_body_root: "/mnt/code-luoxi-pegasus/MAC_ACM_MM/data/sam3d_body/inference"
  ann_file_root: "/mnt/code-luoxi-pegasus/MAC_ACM_MM/data/annotations/"

  img_size: 224
  num_frames: 32 # number of frames to sample from each video

  load_frames: false
  load_2d_kpt: false
  load_3d_kpt: true

  num_workers: 32
  batch_size: 32

  coarse_class_num : 7 # number of coarse classes for dualvideo
  fine_class_num : 52 # number of fine classes for dualvideo

model:
  name: body_part_mamba # body_part_mamba or dual_video

train:
  # Training config
  max_epochs: 50 # numer of epochs of training
  gpus: 1

# Used only when model.name=pose2equip

body_part_mamba:
  num_joints: 15
  mamba_model_name: "mamba_ssm/moge2"
  mamba_freeze: true
  mamba_image_size: 224

log_path: logs/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
