# hydra config
hydra:
  run:
    dir: ${log_path} # the log path, used for log and checkpoint
  sweep:
    dir: logs/
    subdir: ${experiment}/${now:%Y-%m-%d}/${now:%H-%M-%S}

loss:
  lr: 0.001
  weight_decay: 0.01

  fine_loss_weight: 1.0
  coarse_loss_weight: 0.5

data:
  video_root: "/mnt/code-luoxi-pegasus/MAC_ACM_MM/data/video"
  sam3d_body_root: "/mnt/code-luoxi-pegasus/MAC_ACM_MM/data/sam3d_body/inference"
  ann_file_root: "/mnt/code-luoxi-pegasus/MAC_ACM_MM/data/annotations/"

  img_size: 224
  num_frames: 16 # number of frames to sample from each video

  load_frames: true 
  load_2d_kpt: false
  load_3d_kpt: false

  num_workers: 16
  batch_size: 16

  coarse_class_num : 7 # number of coarse classes for dualvideo
  fine_class_num : 52 # number of fine classes for dualvideo

model:
  backbone: dualvideo # dual2pose, pose2equip

train:
  # Training config
  max_epochs: 50 # numer of epochs of training
  gpus: 2

# Used only when model.backbone=pose2equip
dualvideo:
  num_joints: 15
  dino_model_name: facebook/dinov2-base
  dino_freeze: true
  dino_image_size: 224

log_path: logs/${model.backbone}/${now:%Y-%m-%d}/${now:%H-%M-%S}
